lxqt/liblxqt

- cmake/modules/LXQtTranslateDesktop.cmake
https://www.gnu.org/software/grep/manual/grep.html#Output-Line-Prefix-Control
> lxqt_translate_desktop: pass -h instead of --no-filename to grep which is compatible with Busybox

- lxqtsettings.cpp
- lxqtsettings.h
This is to fix lxde/lxqt#441 - [Regression] All LXQt::Settings and QSettings file change monitoring stop working.
https://github.com/lxde/lxqt/issues/441
> Workaround Qt 5.4 issue: Re-add a config file to the file watcher if it's already deleted to get proper change notifications.

- addplugindialog/lxqtaddplugindialog.cpp
- addplugindialog/lxqtaddplugindialog.h
references lxde/lxqt#536, lxde/lxqt#552 (and maybe others)
coupled with (must be merged first) lxde/lxqt-panel#160
Added viewing of delegated context menu for each plugin type:
- in list user can invoke context menu (right-click, 'menu' key) to manage all plugins of current type
Issues/questions:
- the 'Add widget' button now may be obsolete
- the context menu may be a bit tricky for users -> should we add a note somewhere about it?
- i had just a quick search if the dialog is used elsewhere in lxqt and found nothing but `lxqt-panel`. Should we be backward compatible (=> leave old overloads for `pluginAdded`, `pluginRemoved` & `setPluginsInUse`)
> addplugindialog: support for managing plugins

- lxqtgridlayout.cpp
In case stretching is active and for cells rows/cols * itemHeight/itemWidth != height/width
not all possible space was used. This can cause that we are not able to properly style
elements see lxde/lxqt#597
closes lxde/lxqt#597
> gridlayout: avoid empty margins when stretching is active

- cmake/modules/LXQtTranslateDesktop.cmake
Accidentially closed my previous pull request. Here it is refreshed.
Even if the .desktop files are for machine consumption only I prefer the languages sorted.
This also provides identical build results which don't depend on physical file order.
> Sort .desktop translations.

- lxqtsettings.cpp
There's lot's of components that don't have an theme file. There's no need
to issue a warning, not even an debug message.
> Removes Cannot open qss file

- AUTHORS
some files in cmake/modules are under BSD-3-clause
GPL isn't used at all
> license fix for AUTHORS

- lxqtgridlayout.cpp
We should be "light" & the QEasingCurve::Linear should be the less resources expensive one.
> gridlayout: Use linear animation

- lxqtsingleapplication.cpp
Needed if the application is hidden (not only minimized), e.g. for lxqt-runner
needed by lxde/lxqt-runner#38
> SingleApplication: Call also QWidget::show on activate

- lxqtsettings.cpp
- lxqtsettings.h
- Same signal settingsChanged() was emitted upon object based change (setValue(), erase()...) and
upon change made by external entity (watching the file changes) => we added other two signals
settingsChangedFromExternal() & settingsChangedByApp() to make these changes distinguishable. The signal settingsChanged() was left for backwards compatibility.
- Emitting of settingsChanged*() signals was delayed to be able to distinguish if change made on file was based upon our write/sync or by external application.
This is needed by lxde/lxqt-panel#294
> settings: Upgrade emitting of "changed" signals

- lxqtsingleapplication.cpp
fixes lxde/lxqt#951
But I'm not sure if this is the right way...the application's `exec()` will return "immediately", but all the initialization (outside of QApplication/.../SingleApplication) will be performed (creating widgets etc.).
> SingleApplication: Use QCoreApplication::exit() instead of ::exit()

- configdialog/lxqtconfigdialog.cpp
- configdialog/lxqtconfigdialog.h
We don't need/want to handle global settings change. lxqt-qtplugin is handling that.
We just need to know that the theme was changed.
> configdialog: Update icons in ThemeChanged event

- lxqtnotification.cpp
Automatic casts tricked the compiler.
> NotificationPrivate: Fixes programming typo

- lxqtsingleapplication.cpp
Save an allocation and helps static analyzers.
> SingleApplication: Only create an DBus adaptor when needed

- lxqtscreensaver.cpp
- lxqtscreensaver.h
It helps with where the implementation details of a library may be hidden
from its users and changes to the implementation can be made to a library
without breaking binary compatibility.
> lxqtscreensaver: Makes it a opaque pointer class

- lxqthtmldelegate.cpp
QStyleOptionViewItemV4 is just a synonym for QStyleOptionViewItem.
Cleaner builds.
> Replaces deprecated QStyleOptionViewItemV4

- lxqtpowermanager.cpp
We don't need to add the Q_OBJECT macro. Just use the
Q_DECLARE_TR_FUNCTIONS macro.
> Fix lupdate warning missing Q_OBJECT macro

- cmake/modules/LXQtTranslateTs.cmake
https://github.com/lxde/translations.git -> https://github.com/lxde/lxqt-l10n.git
This must not be merged before the lxde/translations -> lxde/lxqt-l10n rename.
> translations: Change default translations repository

- CMakeLists.txt
Use homemade Xdg dirs settings fallback by default if Qt < 5.9.0 and
force disabling the workadound for Qt >= 5.9.0 (as from 5.9.0 the
proper XDG_CONFIG_DIRS support is directly in QSettings).
ref. lxde/lxqt#1158
> build: Enable/disable WITH_XDG_DIRS_FALLBACK based on Qt version

- CMakeLists.txt
As liblxqt picks its version from build tools the minimum build tools version is the to be released version
> Bump needed build tools version

- lxqttranslator.cpp
Use the compiled in LXQT_SHARE_TRANSLATIONS_DIR as the last fallback,
t. m. prefer the XDG_DATA_DIRS%LXQT_RELATIVE_SHARE_TRANSLATIONS_DIR in
run-time.
> Translator: Prefer XDG_DATA_DIRS over compiled in path

- lxqtapplication.cpp
Add the application object as receiver to QObject::connect() -> to
remove the connection automaticaly when the application object is
destructed.
W/o the automatic connection removal we could end in SEGFAULT if UNIX
signal is delivered after the QApplication destruction.
(this was a corner case with almost zero probablity, but now the UNIX
signal handling should be 100% correct)
> lxqtapplication: Avoid wrong signal handling

- lxqthtmldelegate.cpp
- w/o calling the QTextDocument::adjustSize() the size computation is
not correct
- the option.rect is not set if only the sizeHint() is needed by Qt
Note: this was revealed while struggling with lxde/lxqt-runner#58
> HtmlDelegate: Fix sizeHint() computation

- lxqtpower/lxqtpower.cpp
- lxqtpower/lxqtpower.h
- lxqtpower/lxqtpowerproviders.cpp
To allow usage of LXQt::Power object inside of lxqt-session (handling
the called method of LXQtSessionProvider) we need to avoid recurently
calling lxqt-session itself.
supersedes the #121 
ref. lxde/lxqt#1311
> lxqtpower: Allow disabling of lxqt-session provider

- CMakeLists.txt
- lxqtpower/lxqtpower.cpp
- lxqtpower/lxqtpower.h
- lxqtpower/lxqtpowerproviders.cpp
- resources/power.conf
Added the new action PowerMonitorOff, which we currently support only
by the using the external command: xset dpms force off (that means only
CustomProvider does currently provide this action).
The used command is defaultly set in the global config file
/usr/share/lxqt/power.conf.
Note: this is X specific, but downstream can easily change the default
command by providing /etc/lxqt/power.conf...
needed by lxde/lxqt-powermanagement#62
> lxqtpower: Add support for turning monitor(s) off

- CMakeLists.txt
Specify the output path of the polkit file.
> lxqtbacklight: Fix a FTBFS in superbuild mode

- CMakeLists.txt
lxqt-build-tools version should probably be updated. And the minimum required here, updated accordingly,
> No in source builds

- lxqtbacklight/linux_backend/driver/lxqtbacklight_backend.c
The actual backlight is not used.
> lxqtbacklight: Remove not used code

- lxqtbacklight/linux_backend/linuxbackend.cpp
Fixes https://github.com/lxqt/lxqt/issues/1485
Instead of filtering out values outside the range, normalize them to deal with `QSlider` correctly.
> Normalize backlight value

- lxqtbacklight/linux_backend/linuxbackend.cpp
Taking into account that the strings are Latin1 encoded.
> lxqt-backlight: Simplify string construction

- CMakeLists.txt
- configdialog/lxqtconfigdialog.cpp
- configdialog/lxqtconfigdialog.h
- lxqtapplication.cpp
- lxqtautostartentry.cpp
- lxqtbacklight/linux_backend/linuxbackend.cpp
- lxqtnotification.cpp
- lxqtplugininfo.cpp
- lxqtplugininfo.h
- lxqtpower/lxqtpowerproviders.cpp
- lxqtpowermanager.cpp
- lxqtprogramfinder.cpp
- lxqtscreensaver.cpp
- lxqtsettings.cpp
- lxqttranslator.cpp
Disables automatic conversions from 8-bit strings (char *) to unicode
QStrings.
Disables automatic conversion from QString to 8-bit strings (char *).
Disables automatic conversions from QByteArray to const char * or const
void *.
Disables automatic conversions from QString (or char *) to QUrl.
Use QStringBuilder for more efficient string creation.
It make us aware of string and encoding conversions.
> Don't use automatic string conversions

- AUTHORS
In https://github.com/lxqt/liblxqt/pull/66:
> some files in cmake/modules are under BSD-3-clause
Looks like those CMake files are removed after liblxqt moved to lxqt-build-tools https://github.com/lxqt/liblxqt/pull/109.
> Fix licenses

- lxqtapplication.cpp
..as it produces (useless) debug.log file. And the file is/was misplaced
in .config dir anyway.
For debugging anyone can redirect stdout/stderr to whereever he/she
wants. For message formatting we should use the QT_MESSAGE_PATTERN
(https://doc.qt.io/qt-5/debug.html#warning-and-debugging-messages).
closes lxqt/lxqt#1701
> lxqtapplication: Remove message handler

- lxqtpowermanager.cpp
Because, otherwise, it'll be "No" with Gnome button layout, which is a valid layout in Qt and can be used anywhere.
Fixes https://github.com/lxqt/lxqt-session/issues/249
> Set default button to Yes in leave dialogs

- configdialog/lxqtpageselectwidget.cpp
- configdialog/lxqtpageselectwidget.h
Closes https://github.com/lxqt/lxqt-config/issues/499
We just need to add twice the frame width to the viewport size hint because we've added the scrollbar thickness in `PageSelectWidget::viewportSizeHint`.
Also, transient scrollbars are taken into account — believe me, they exist ;) and they should have been taken into account by Qt in the first place (= Qt bug).
> Set size hint of selection widget correctly

- CMakeLists.txt
- cmake/lxqt-config.cmake.in
- lxqtsingleapplication.cpp
* Don't use X11 libs.
* Don't build LXQt::ScreenSaver. It uses the X11 screensaver protocol.
* Use symbols from the KWindowSystem class instead of NET class. The
NETWM header is available on XCB only.
> Make it build on macOS

- CMakeLists.txt
- lxqtbacklight.cpp
Changes:
- Do not compile the linux backend for the backlight driver on the Hurd.
Justification:
- Fails to compile on the Hurd (`PATH_MAX` is not defined on the Hurd)
- The backend uses the `/sys/` special file system, which is not provided by the Hurd.
Alternative approach:
- Modify `open_driver_file` in [`lxqtbacklight/linux_backend/driver/libbacklight_backend.c`](https://github.com/lxqt/liblxqt/blob/2b805344d81362237a21dcbed097f2fdd36cb4a4/lxqtbacklight/linux_backend/driver/libbacklight_backend.c) to not use `PATH_MAX`.
> Fix compilation error on Debian GNU/Hurd

- lxqtscreensaver.cpp
* Show a different message for lockers/screensavers other than
xdg-screensaver.
* Remove an unused comment. That comment was serving as a reference for
return codes of xdg-screensaver. It's no longer relevant after #227.
> lxqtscreensaver: improve messages for errors from lock_command

- lxqtbacklight/linux_backend/driver/lxqtbacklight_backend.c
A part of conditional expression is always true
> Remove redundant check

- lxqtpowermanager.cpp
It maintains functionality. It uses the default/primary screen.
> Remove deprecated QDesktopWidget

- lxqtscreensaver.cpp
QMessageBox::exec() is blocking so, it's safe to delete it.
> lxqtscreensaver: Fix a memory leak

- lxqtnotification.cpp
- lxqtnotification.h
- lxqtnotification_p.h
Adds an asynchronous version of Notification::serverInfo() call which
will not hang up app for a while if there is no daemon running.
> lxqtnotification: async API for querying serverInfo

- lxqtrotatedwidget.h
Using 0/nullptr is deprecated.
> Use QFlags default constructor

- lxqtpower/lxqtpowerproviders.cpp
- lxqtscreensaver.cpp
Since we have to split the command ourselves, checking for a empty command,
makes sense now.
> Don't use deprecated QProcess methods

- lxqtsettings.cpp
Copy assignment operators must be protected against self-assignment.
Good practice.
> LXQtTheme: Handle self assignment properly

- lxqtpower/lxqtpowerproviders.cpp
Sending invalid QVariant over dbus let systemd provider to fail retrieving informations. journalctl list warnings on that calls. This (easy) patch solves this.
> Fix dbus errors with invalid QVariant data sent over it

- lxqtsettings.h
..to make it possible to use new Qt5(onwards) signal/slot syntax.
Note: needed for e.g. lxqt/lxqt-powermanagement#227
> lxqtsettings: Make GlobalSettings public (export symbols)

- lxqtsettings.cpp
This reverses https://github.com/lxqt/liblxqt/commit/ead8ceefa2a142b59e346b9df39a0070de709c73. After a discussion with @yan12125, it turned out to be redundant (especially see https://github.com/lxqt/lxqt-themes/issues/69#issuecomment-1114882618).
> Reversed case-insensitivity commit

- lxqtscreensaver.cpp
Fixes https://github.com/lxqt/lxqt-powermanagement/issues/342
The error message is shown when trying to lock screen from menu, runner or as action in powermanagement > lid > lock screen
> Show error under wayland

- configdialog/lxqtconfigdialog.cpp
- configdialog/lxqtconfigdialog.h
- configdialog/lxqtconfigdialogcmdlineoptions.cpp
- lxqtapplication.cpp
- lxqtautostartentry.cpp
- lxqtbacklight/linux_backend/linuxbackend.cpp
- lxqtglobals.h
- lxqtnotification.cpp
- lxqtplugininfo.cpp
- lxqtplugininfo.h
- lxqtpower/lxqtpowerproviders.cpp
- lxqtpowermanager.cpp
- lxqtscreensaver.cpp
- lxqtsettings.cpp
- lxqtsingleapplication.cpp
- lxqttranslator.cpp
See https://doc.qt.io/qt-6/qlatin1string.html.
Also, `QStringLiteral` is used where a function is not overloaded to take `QLatin1StringView`. See the note below https://doc.qt.io/qt-6/qlatin1stringview.html#details for the reason.
> Replaced `QLatin1String` with `QLatin1StringView`

- lxqtgridlayout.cpp
With a horizontal layout, the item width was increased by one pixel when there was empty space, but that one pixel wasn't taken into account anywhere else — and similarly with a vertical layout. I removed it, and the occasional position shifts disappeared from task buttons of lxqt-panel.
In short, the original calculations inside `GridLayout::setGeometry` didn't seem correct to me.
Fixes https://github.com/lxqt/lxqt-panel/issues/2065
> Fixed setting of item geometries in grid layout

- lxqtautostartentry.cpp
Related to https://github.com/lxqt/lxqt-session/issues/563
NOTE: This should be used only with an upcoming `lxqt-session` patch that uses it.
> Disable autostart entries only for LXQt

- CHANGELOG
- CMakeLists.txt
- cmake/lxqt-config.cmake.in
- lxqtapplication.cpp
- lxqtapplication.h
- lxqtnotification.cpp
- lxqtnotification.h
- lxqtnotification_p.h
- lxqtsettings.cpp
Typo fixes to comments/text and identifiers. Half of the changes are to CHANGELOG.
Affected files:
- CHANGELOG
- CMakeLists.txt
- lxqtapplication.h
- lxqtnotification.cpp
- lxqtnotification.h
- lxqtnotification_p.h
- lxqtsettings.cpp
- cmake/lxqt-config.cmake.in
> Typo fixes
