addplugindialog/lxqtaddplugindialog.cpp, addplugindialog/lxqtaddplugindialog.ui
Enhancements:
* It selects the first row by default;
* It uses Alternating Row Colors for enhanced readability;
* Adjustable resize mode.
=> Enhance the panel Add Plugin Dialog

lxqtapplication.cpp, lxqtapplication.h
=> LxQt::Application: unix signal handling & quit

translations/liblxqt_el.ts
=> Update Greek (el) translation

lxqttranslator.cpp
@SokoloffA , @luis-pereira  - ok with the change? Copied the license from the header
=> licensefix for lxqttranslator.cpp

translations/liblxqt_fr_FR.ts
Minor fix in French translation file
=> Fix typos in translations/liblxqt_fr_FR.ts

configdialog/lxqtconfigdialog.cpp
Make it resilient to null pointers pages.
=> config dialog: Protect against null pages add.

lxqtgridlayout.cpp, lxqtgridlayout.h
Support for visualizated item moving.
Maybe we should provide `LXQt::ItemMoveAnimation` as a standalone class as it can be usefull for LXQt components (the logic is stolen from lxqt-panel anyway).
=> Layout updates

lxqtsettings.cpp
fixes lxde/lxqt#940
Do I miss something or is the reasoning (i've written into the commit log message) 100% valid?
=> LXQtTheme: Remove (outdated) "singleclick" qss assembly

configdialog/lxqtconfigdialog.ui, configdialog/lxqtpageselectwidget.cpp, configdialog/lxqtpageselectwidget.h
=> configdialog: Fix icon bar sizing

lxqtpower/lxqtpowerproviders.cpp
=> lxqtpower: Removes unused stuff

lxqtapplication.cpp
Correctly dispose all resources that we acquired -> close also the socketpair file descriptors.
=> application: Correct signal handling & clean-up

lxqtgridlayout.cpp, lxqthtmldelegate.cpp
With this we will correctly support RightToLeft layout direction.
First step for lxde/lxqt#421
=> GridLayout: Take layoutDirection into account

lxqtgridlayout.cpp, lxqtgridlayout.h, lxqthtmldelegate.cpp
It's good to know if the animated transition is currently in progress.
It needs to go after the #96
This is needed for lxde/lxqt-panel#357
=> GridLayout: Store current animation flag

dbus/org.freedesktop.Notifications.xml
Just following moc suggestion. And making a warning go away.
=> Update DBus Notify method annotation name

CMakeLists.txt
needed at least for lxqt-panel and actions
=> Bump minimum qtxdg version to 3.1.0

CMakeLists.txt
Mark the DBUS_SOURCES files with SKIP_AUTOGEN.
Fix for https://github.com/lxde/lxqt/issues/1420.
=> cmake: Handle CMP0071

CMakeLists.txt, configdialog/lxqtconfigdialog.cpp, lxqtautostartentry.cpp, lxqtgridlayout.cpp, lxqtplugininfo.cpp, lxqtpower/lxqtpower.cpp, lxqtprogramfinder.cpp, lxqtsettings.cpp, lxqttranslator.cpp
It will be deprecated soon. Replacing it with the ranged for.
=> Drop foreach use

CMakeLists.txt, lxqtgridlayout.cpp, lxqtpower/lxqtpower.cpp, lxqtsettings.cpp, lxqttranslator.cpp
Bump required Qt version to 5.7.1 and lxqt-build-tools to 0.4.1.
=> Use qAsConst()

CMakeLists.txt
Makes PolkitQt5-1 a (build time) dependency.
=> Use PolkitQt5-1 policy files install directory

CMakeLists.txt
Stop using QUIET with find_package()
=> Don't find packages quietly

lxqtapplication.cpp, lxqtbacklight.cpp, lxqtbacklight/linux_backend/linuxbackend.cpp, lxqtnotification.cpp, lxqtpowermanager.cpp, lxqtscreensaver.cpp, lxqtscreensaver.h
It has better performance and better compile time check.
=> Use the new signal and slot syntax

lxqthtmldelegate.cpp
Closes https://github.com/lxqt/lxqt/issues/1550
Texts and icons are vertically centered and item heights are correctly calculated in terms of wrapped text heights and icon heights. Unconditional using of `QTextDocument::adjustSize()` was wrong (actually, it could be removed). Moreover, `QStyle::drawControl()` should not be used for drawing the panel.
Please also note that Qt has an HTML bug, which is explained in a code comment.
=> Position, alignment and size fixes for HTML delegate

configdialog/lxqtpageselectwidget.cpp, configdialog/lxqtpageselectwidget.h
Fixes https://github.com/lxqt/lxqt/issues/1510
=> Fixed config dialog select widget cells

lxqthtmldelegate.cpp
Fixes https://github.com/lxqt/lxqt/issues/1649
=> Added missing text color of our HTML delegate

lxqtgridlayout.cpp
setSpacing() is a base member of QLayout.  It would be nice if LXQt::GridLayout made use of this property.
Since existing code will assume that LXQt::GridLayout does *not* use any spacing, set the property to 0 by default in the constructor.
=> Make setSpacing() work with LXQt::GridLayout.

lxqtscreensaver.cpp
Ref: https://github.com/lxqt/lxqt/issues/1378
=> Fix error messages for screensavers

lxqtscreensaver.cpp
The first step towards https://github.com/lxqt/lxqt/issues/1378.
=> lxqtscreensaver: allow custom lock command

CMakeLists.txt, configdialog/lxqtconfigdialog.cpp, configdialog/lxqtconfigdialog.h, configdialog/lxqtpageselectwidget.h, lxqtapplication.cpp, lxqtapplication.h, lxqtbacklight.cpp, lxqtbacklight.h, lxqtbacklight/linux_backend/linuxbackend.cpp, lxqtbacklight/linux_backend/linuxbackend.h, lxqtbacklight/virtual_backend.h, lxqtnotification.cpp, lxqtnotification.h, lxqtnotification_p.h, lxqtpower/lxqtpower.h, lxqtpower/lxqtpowerproviders.h, lxqtpowermanager.h, lxqtscreensaver.cpp, lxqtscreensaver.h, lxqtsettings.cpp, lxqtsettings.h
Don't use emit, signal and slot. They collide with glib.
=> Don't use Qt keywords

lxqtscreensaver.cpp
Fixes https://github.com/lxqt/lxqt/issues/1792
=> Prevent crash when closing screen saver error message

translations/liblxqt_tr.ts
Updated Turkish translations for more regular Turkish.
=> Update Turkish translations

lxqtpower/lxqtpower.cpp, lxqtpower/lxqtpower.h, lxqtpower/lxqtpowerproviders.cpp, resources/power.conf
Support for https://github.com/lxqt/lxqt-powermanagement/pull/196.
=> lxqtpower: Adds a Show Leave dialog action

lxqtnotification.cpp, lxqtnotification_p.h, lxqtplugininfo.cpp, lxqtsettings.cpp, lxqtsettings.h
Good practice and a minor performance improvement.
=> Use const references where possible

lxqtsingleapplication.cpp
.. to be able to shutdown the application cleanly.
=> lxqtsingleapplication: Use "handle quit signals" constructor

lxqtsettings.cpp
Fixes https://github.com/lxqt/liblxqt/issues/302
=> support relative pathes in wallpaper.cfg

configdialog/lxqtconfigdialog.cpp, configdialog/lxqtconfigdialog.h, configdialog/lxqtconfigdialogcmdlineoptions.cpp, lxqtapplication.cpp, lxqtautostartentry.cpp, lxqtbacklight/linux_backend/linuxbackend.cpp, lxqtglobals.h, lxqtnotification.cpp, lxqtplugininfo.cpp, lxqtplugininfo.h, lxqtpower/lxqtpowerproviders.cpp, lxqtpowermanager.cpp, lxqtscreensaver.cpp, lxqtsettings.cpp, lxqttranslator.cpp
=> Introduces a new macro for QLatin1StringView (QL1SV)

lxqtscreensaver.cpp
Just a rebased version of  https://github.com/lxqt/liblxqt/pull/256
Parts needed:
```
lock_command=i3lock-fancy
lock_command_wayland=swaylock
```
which will need https://github.com/lxqt/liblxqt/pull/346 and the GUI.
=> Add custom screenlocker
